import type { Problem } from './check.js';
import type { GateResult } from './gate.js';
import { TRANCHES, type Baseline, type TraceModel } from './model.js';
import { type Trace, traceOf } from './state.js';

export interface PackDocument {
  readonly path: string;
  readonly body: string;
}

export interface PackInput {
  readonly version: string;
  readonly commit: string;
  readonly baseline: Baseline;
  readonly result: GateResult;
  readonly model: TraceModel;
}

/**
 * A markdown table cell, made safe for the one thing that would otherwise break the table: an
 * unescaped `|` in freeform text (a statement, a reason, a problem's detail) is exactly the
 * character `parse/table.ts` splits rows on, so a literal one here is escaped the same way that
 * parser expects to find it escaped. A newline is collapsed to a space, because a table row is one
 * line.
 */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function table(headers: string[], rows: string[][]): string {
  const line = (cells: string[]): string => `| ${cells.map(cell).join(' | ')} |`;
  return [line(headers), line(headers.map(() => '---')), ...rows.map(line)].join('\n');
}

const passed = (result: GateResult): boolean =>
  result.met === result.total && result.declarationProblems.length === 0;

/**
 * How a requirement is shown to be met, for the matrix and results documents. `test`, the default,
 * lists where a test names it - `state.ts`'s citations, the same ones `pnpm trace show` prints.
 * `inherited` and `attestation` are declared in the baseline itself, not discovered from the corpus,
 * so this reads the baseline's own row rather than anything `traceOf` computed - an attestation's
 * `by` is the whole evidential content of the row, and printing it is the only reason this function
 * takes the baseline at all.
 */
function evidenceFor(id: string, baseline: Baseline, trace: Trace | undefined): string {
  const declared = baseline.verification.find((row) => row.id === id);
  if (declared?.kind === 'attestation') return `Attested by ${declared.by}`;
  if (declared?.kind === 'inherited') return `Inherited from ${declared.by}`;
  if (trace === undefined || trace.citations.length === 0) return 'No test names it';
  return trace.citations.map((citation) => `${citation.file}:${citation.line}`).join('; ');
}

/**
 * The gate's per-requirement verdict, in prose rather than a bare pass/fail flag - the reason a
 * requirement is unmet is exactly what an auditor asks next, and `result.unmet` already carries it.
 * The two declaration-problem kinds that drop an id from `total` entirely (`both-included-and-
 * excluded`, `duplicate-verification`) never reach `unmet`, so they are checked second, from the
 * same list `formatGate` prints under its own heading.
 */
function verdictFor(id: string, result: GateResult): string {
  const unmet = result.unmet.find((entry) => entry.id === id);
  if (unmet !== undefined) return `Unmet - ${unmet.why}`;
  const problem = result.declarationProblems.find((entry) => entry.id === id);
  if (problem !== undefined) return `Declaration problem - ${problem.detail}`;
  return 'Met';
}

function readme(input: PackInput): PackDocument {
  const { version, commit, baseline, result } = input;
  const ok = passed(result);
  const dropped = baseline.included.length - result.total;
  const droppedNote = dropped > 0 ? ` (${dropped} row(s) dropped by a declaration problem)` : '';

  const lines = [
    `# Evidence pack: ${version}`,
    '',
    `Generated at commit \`${commit}\`, against baseline \`${baseline.name}\` (declared` +
      ` ${baseline.declaredAt}).`,
    '',
    `**${ok ? 'PASSED' : 'FAILED'}** - \`pnpm trace gate\` reports ${result.met} of ${result.total}` +
      ` included requirement(s) met${droppedNote}, with ${result.declarationProblems.length}` +
      " problem(s) in the baseline's own declaration.",
    '',
    'This directory is generated by `pnpm trace pack` and committed as a point-in-time record of' +
      ' one run. It is not compared against a fresh generation the way `trace.json` is compared' +
      ' against a fresh compile - `pnpm trace pack` refuses to run on a dirty working tree, so' +
      ' regenerating this pack for the same release replaces it with a new run from a clean tree,' +
      ' at the commit being released.',
    '',
    '## What is in this pack',
    '',
    `- \`README.md\` - this file: the version, the commit, the baseline and whether it passed.`,
    '- `matrix.md` - one row per requirement this baseline claims: its statement, tranche, the' +
      " design that answers it, the test or declaration that verifies it, and the gate's verdict.",
    '- `gaps.md` - every problem in the corpus, every requirement this baseline explicitly excludes' +
      ' and why, and how many in-force requirements this release simply does not claim, by tranche.',
    '- `results.md` - the test evidence behind the matrix, one row per citation.',
    '',
    'This pack is evidence about a **declared scope**, not about the whole product: see `gaps.md`' +
      ' for what it does not cover, and `docs/specification/baselines/README.md` for what a' +
      ' baseline is.',
  ];

  return { path: `docs/trace/${version}/README.md`, body: `${lines.join('\n')}\n` };
}

function matrix(input: PackInput): PackDocument {
  const { version, baseline, result, model } = input;
  const rows = [...baseline.included]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((inclusion) => {
      const trace = traceOf(inclusion.id, model);
      const statement = trace?.requirement.statement ?? '(requirement not found in the corpus)';
      const tranche = trace?.requirement.tranche ?? 'n/a';
      const design = trace?.design ?? 'No design claims it';
      return [
        `**${inclusion.id}**`,
        statement,
        tranche,
        design,
        evidenceFor(inclusion.id, baseline, trace),
        verdictFor(inclusion.id, result),
      ];
    });

  const lines = [
    `# Traceability matrix: ${version}`,
    '',
    `Baseline \`${baseline.name}\`, declared ${baseline.declaredAt}. One row per requirement this` +
      ' release is answerable for - nothing outside it appears here; see `gaps.md` for what is not' +
      ' claimed.',
    '',
    table(['ID', 'Statement', 'Tranche', 'Design', 'Evidence', 'Verdict'], rows),
  ];

  return { path: `docs/trace/${version}/matrix.md`, body: `${lines.join('\n')}\n` };
}

function gaps(input: PackInput): PackDocument {
  const { version, baseline, result, model } = input;
  const includedIds = new Set(baseline.included.map((inclusion) => inclusion.id));
  const excludedIds = new Set(baseline.excluded.map((exclusion) => exclusion.id));

  const problemRows = result.problems.map((problem: Problem) => [
    problem.kind,
    problem.id,
    problem.detail,
  ]);

  const excludedRows = [...baseline.excluded]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((exclusion) => [`**${exclusion.id}**`, exclusion.reason]);

  // Excluded requirements are named above, in the Excluded table - counting them again here would
  // double-count them: once by name, once inside a tally that claims to be everything named nowhere
  // in this pack.
  const outOfBaseline = model.requirements.filter(
    (requirement) =>
      requirement.status === 'Specified' &&
      !includedIds.has(requirement.id) &&
      !excludedIds.has(requirement.id),
  );
  const tallyRows = TRANCHES.map((tranche) => [
    tranche,
    String(outOfBaseline.filter((requirement) => requirement.tranche === tranche).length),
  ]).filter(([, count]) => count !== '0');

  const lines = [
    `# Gaps: ${version}`,
    '',
    `Baseline \`${baseline.name}\`, declared ${baseline.declaredAt}. What this evidence pack does` +
      ' not claim, so that an absence here reads as declared rather than as forgotten.',
    '',
    '## Corpus problems',
    '',
    'Every defect `pnpm trace check` finds in the corpus, whether or not it touches this baseline -' +
      ' `pnpm trace gate` only fails on the ones that do.',
    '',
    result.problems.length === 0
      ? 'No corpus problems.'
      : table(['Kind', 'ID', 'Detail'], problemRows),
    '',
    '## Excluded',
    '',
    'Requirements somebody would reasonably expect to find in this baseline, and why this release' +
      ' does not claim them. See `docs/specification/baselines/README.md` for how this differs from' +
      ' simply being out of baseline.',
    '',
    baseline.excluded.length === 0
      ? 'Nothing explicitly excluded.'
      : table(['ID', 'Reason'], excludedRows),
    '',
    '## Everything else out of baseline',
    '',
    `${outOfBaseline.length} in-force requirement(s) this release does not claim at all, named` +
      ' nowhere in this pack because a baseline for an early release does not need one row per' +
      ' requirement it has not reached yet. Counted by tranche, not by identifier:',
    '',
    tallyRows.length === 0 ? 'None.' : table(['Tranche', 'In force, out of baseline'], tallyRows),
  ];

  return { path: `docs/trace/${version}/gaps.md`, body: `${lines.join('\n')}\n` };
}

function results(input: PackInput): PackDocument {
  const { version, baseline, result, model } = input;

  const rows = [...baseline.included]
    .sort((a, b) => a.id.localeCompare(b.id))
    .flatMap((inclusion) => {
      const trace = traceOf(inclusion.id, model);
      const declared = baseline.verification.find((row) => row.id === inclusion.id);
      const verdict = verdictFor(inclusion.id, result);

      if (declared?.kind === 'attestation' || declared?.kind === 'inherited') {
        return [
          [
            `**${inclusion.id}**`,
            declared.kind,
            evidenceFor(inclusion.id, baseline, trace),
            verdict,
          ],
        ];
      }
      if (trace === undefined || trace.citations.length === 0) {
        return [[`**${inclusion.id}**`, 'test', 'No test names it', verdict]];
      }
      return trace.citations.map((citation) => [
        `**${inclusion.id}**`,
        citation.kind,
        `${citation.file}:${citation.line}`,
        verdict,
      ]);
    });

  const lines = [
    `# Test results: ${version}`,
    '',
    `Baseline \`${baseline.name}\`, declared ${baseline.declaredAt}. One row per piece of evidence` +
      ' behind the matrix: a citation naming a requirement in its test title or a `rule:` field, or' +
      " the baseline's own declaration for a requirement no test reaches. The verdict is the" +
      " gate's, computed from whether every test naming that requirement passed - not a per-test" +
      ' status, because a requirement is verified only when all of its evidence is.',
    '',
    table(['ID', 'Kind', 'Evidence', 'Verdict'], rows),
  ];

  return { path: `docs/trace/${version}/results.md`, body: `${lines.join('\n')}\n` };
}

/**
 * The evidence pack: four documents an auditor asks for, as strings rather than files. Pure - no
 * `node:fs`, no git - so every document is testable as a string; `cli.ts` writes them and supplies
 * the commit and version this function never reads for itself.
 */
export function packDocuments(input: PackInput): PackDocument[] {
  return [readme(input), matrix(input), gaps(input), results(input)];
}
