import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { codePoints } from './cmap.js';
import type { Ranges } from './covers.js';
import { PINNED_FONT_FILES } from './pinned.js';

export { codePoints } from './cmap.js';
export { capHeight } from './metrics.js';

/**
 * Where the pinned files are: `files/` beside this package's `src` and `dist` alike, so the worker finds
 * them in the workspace and in the deployed image, where `pnpm deploy` copies the package's `files`.
 */
export const FONT_DIRECTORY = fileURLToPath(new URL('../files/', import.meta.url));

/**
 * What each pinned family covers, read from its files' character maps: a character only where **every**
 * face of the family maps it to a glyph, a heading's bold as well as a paragraph's regular, as the worker's
 * `covers` asks (themes 1, ruling R6). As ranges, first to last inclusive, in order.
 */
export async function coverageOfFiles(directory: string): Promise<Map<string, Ranges>> {
  const byFamily = new Map<string, Set<number>[]>();
  for (const pinned of PINNED_FONT_FILES) {
    const set = codePoints(await readFile(join(directory, pinned.file)));
    byFamily.set(pinned.family, [...(byFamily.get(pinned.family) ?? []), set]);
  }
  return new Map(
    [...byFamily].map(([family, [first = new Set<number>(), ...rest]]) => [
      family,
      ranges([...first].filter((codePoint) => rest.every((set) => set.has(codePoint)))),
    ]),
  );
}

function ranges(codePoints: number[]): Ranges {
  const sorted = [...codePoints].sort((a, b) => a - b);
  const out: [number, number][] = [];
  for (const codePoint of sorted) {
    const last = out.at(-1);
    if (last && last[1] === codePoint - 1) last[1] = codePoint;
    else out.push([codePoint, codePoint]);
  }
  return out;
}

/** `coverage.ts` as the generator writes it: one family to a line, in the pinned list's order. */
export function renderCoverage(coverage: ReadonlyMap<string, Ranges>): string {
  const families = [...new Set(PINNED_FONT_FILES.map((each) => each.family))];
  const lines = families.map(
    (family) =>
      `  '${family}': [${(coverage.get(family) ?? []).map(([first, last]) => `[${first}, ${last}]`).join(', ')}],`,
  );
  return [
    '// Generated by `pnpm --filter @alloy-works/fonts generate` from the pinned files: never edited by',
    "// hand. coverage.test.ts regenerates it and fails on a difference, as openapi.json's test does.",
    '',
    "import type { Ranges } from './covers.js';",
    '',
    '/** The characters each pinned family covers, as ranges, first to last inclusive (`coverageOfFiles`). */',
    'export const COVERAGE: Readonly<Record<string, Ranges>> = {',
    ...lines,
    '};',
    '',
  ].join('\n');
}
